INSERT INTO cities (id, name, country, slug, is_active)
VALUES
  (uuid_generate_v4(), 'London',       'UK',           'london',       true),
  (uuid_generate_v4(), 'Manchester',   'UK',           'manchester',   true),
  (uuid_generate_v4(), 'New York',     'USA',          'new-york',     true),
  (uuid_generate_v4(), 'Los Angeles',  'USA',          'los-angeles',  true),
  (uuid_generate_v4(), 'Chicago',      'USA',          'chicago',      true),
  (uuid_generate_v4(), 'Miami',        'USA',          'miami',        true),
  (uuid_generate_v4(), 'Toronto',      'Canada',       'toronto',      true),
  (uuid_generate_v4(), 'Vancouver',    'Canada',       'vancouver',    true),
  (uuid_generate_v4(), 'Paris',        'France',       'paris',        true),
  (uuid_generate_v4(), 'Berlin',       'Germany',      'berlin',       true),
  (uuid_generate_v4(), 'Amsterdam',    'Netherlands',  'amsterdam',    true),
  (uuid_generate_v4(), 'Barcelona',    'Spain',        'barcelona',    true),
  (uuid_generate_v4(), 'Madrid',       'Spain',        'madrid',       true),
  (uuid_generate_v4(), 'Rome',         'Italy',        'rome',         true),
  (uuid_generate_v4(), 'Dubai',        'UAE',          'dubai',        true),
  (uuid_generate_v4(), 'Abu Dhabi',    'UAE',          'abu-dhabi',    true),
  (uuid_generate_v4(), 'Riyadh',       'Saudi Arabia', 'riyadh',       true),
  (uuid_generate_v4(), 'Singapore',    'Singapore',    'singapore',    true),
  (uuid_generate_v4(), 'Tokyo',        'Japan',        'tokyo',        true),
  (uuid_generate_v4(), 'Seoul',        'South Korea',  'seoul',        true),
  (uuid_generate_v4(), 'Bangkok',      'Thailand',     'bangkok',      true),
  (uuid_generate_v4(), 'Mumbai',       'India',        'mumbai',       true),
  (uuid_generate_v4(), 'Delhi',        'India',        'delhi',        true),
  (uuid_generate_v4(), 'Sydney',       'Australia',    'sydney',       true),
  (uuid_generate_v4(), 'Melbourne',    'Australia',    'melbourne',    true),
  (uuid_generate_v4(), 'São Paulo',    'Brazil',       'sao-paulo',    true),
  (uuid_generate_v4(), 'Mexico City',  'Mexico',       'mexico-city',  true)
ON CONFLICT (slug) DO NOTHING;
